/*
 * Complete Academic Program Breakdown for a UFID
 * Filtered by UFID
 *
 */           
SELECT A.EMPLID
      ,B.TERM_CD as EFFECTIVE_TERM
      ,C.TERM_CD AS END_TERM
      ,E.PROG_STATUS_LD
      ,L.PROG_ACTION_LD
      ,M.PROG_REASON_LD
      ,H.ACAD_CAR_LD 
      ,J.ACAD_GRP_LD 
      ,D.ACAD_PLAN_TYPE_LD
      ,D.ACAD_PLAN_CD
      ,D.ACAD_PLAN_LD
      ,I.ACAD_SPLAN_CD
      ,I.ACAD_SPLAN_LD
      ,A.EFFDT_SID
      ,A.END_EFFDT_SID
      ,A.ACAD_PROG
      ,A.PLAN_SEQUENCE
  FROM CS.WH_F_CPPS A,  CS.WH_D_TERM B, CS.WH_D_TERM C,  CS.WH_D_ACAD_PLAN D, CS.WH_D_PROG_STATUS E,  
  CS.WH_D_ACAD_PROG G,CS.WH_D_ACAD_CAR H, CS.WH_D_ACAD_SPLAN I, CS.WH_D_ACAD_GRP J, CS.WH_D_MDM_PERSON K,
  CS.WH_D_PROG_ACTION L, CS.WH_D_PROG_REASON M
WHERE A.EFF_TERM_SID = B.TERM_SID
  AND A.END_EFF_TERM_SID = C.TERM_SID
  AND A.ACAD_PLAN_SID = D.ACAD_PLAN_SID
  AND A.PROG_STATUS_SID = E.PROG_STATUS_SID
  AND A.ACAD_PROG_SID = G.ACAD_PROG_SID
  AND A.ACAD_CAR_SID = H.ACAD_CAR_SID
  AND A.ACAD_SPLAN_SID = I.ACAD_SPLAN_SID
  AND A.ACAD_GRP_SID = J.ACAD_GRP_SID
  AND A.PERSON_SID = K.PERSON_SID
  AND A.PROG_ACTION_SID = L.PROG_ACTION_SID
  AND A.PROG_REASON_SID = M.PROG_REASON_SID
  AND  K.UFID = :1
order by B.TERM_CD;   