/*
 * Complete Term Breakdown for a UFID
 * Filtered by UFID   
 * Displays the Primary activated academic career program plan information
 *
 */        
 
select B.UFID, E.TERM_CD, D.ACAD_LOAD_LD, A.CUR_GPA, A.CUM_GPA, C.ACAD_GRP_LD AS PRIMARY_ACAD_GROUP, F.ACAD_PLAN_LD AS PRIMARY_ACAD_PLAN, H.DEGREE_LD AS PRIMARY_DEGREE, G.UF_CLASS, 
A.TOT_GRADE_POINTS as GRADE_POINTS, A.TOT_TAKEN_GPA as HOURS_CARRIED, A.UNT_TRNSFR as TRANSER_HOURS, A.UNT_TAKEN_PRGRSS as HOURS_TAKEN, A. UNT_PASSD_PRGRSS AS HOURS_EARNED
from CS.WH_F_ENROLLMENT_TERM A, CS.WH_D_MDM_PERSON B, CS.WH_D_ACAD_GRP C, CS.WH_D_ACAD_LOAD D, CS.WH_D_TERM E, CS.WH_D_ACAD_PLAN F, CS.WH_D_ACAD_LEVEL G, CS.WH_D_DEGREE H
WHERE A.PERSON_SID = B.PERSON_SID
  AND A.ACAD_GRP_SID = C.ACAD_GRP_SID
  AND A.ACAD_LOAD_SID = D.ACAD_LOAD_SID
  AND A.TERM_SID = E.TERM_SID
  AND A.ACAD_PLAN_SID = F.ACAD_PLAN_SID
  AND A.ACAD_LEVEL_BOT_SID = G.ACAD_LEVEL_SID
  AND A.DEGREE_SID = H.DEGREE_SID
  AND B.UFID = :1
  order by TERM_CD;
  